### ISSUE TITLE
Batch Examples: Manual Tests on MATLAB & Octave

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#143]
I think solving issues this way will be really helpful to get one step closer to a green Travis check.

@tanguyduval  On octave, I still need to put `if moxunit_util_platform_is_octave` in batch examples for GUI line, otherwise it fails for some of the methods e.g. IR (not failing for some others interestingly e.g. b0). I also added `more off;` for Octave in the same line. So now that section serves a good purpose in general. I know it is not the best user friendly option, yet it works :) 

I'll keep listing the models that I've tested here, please feel free to contribute:

_General: Octave cannot generate sim lines in batch examples._ 

- **inversion recovery**  
Batch example generation (M/O passed) 
Batch example execution (M/O passed)
Displaying outputs (M/O passed)

- **mt_sat**  
Batch example generation (M/O passed) 
Batch example execution (M/O passed)
Displaying outputs (M/O passed)

- **b0_dem**  
Batch example generation (M/O passed) 
Batch example execution (M/O passed) => Takes considerably more time on Octave
Displaying outputs (M/O passed)

- **b1_dam**  
Batch example generation (M/ passed)  => Octave: Failed. It produces empty script **o_O**
Batch example execution (M/O passed) => Octave: Worked with Matlab generated batch.
Displaying outputs (M/O passed) => Octave: Worked with Matlab generated batch.

- **qmt_bssfp**  
Batch example generation (M/O passed) 
Batch example execution (M/O passed)  
**Octave => 1hr45min. Well, it works and it is for free ^_^ <3
Matlab => ~5 minutes :/**
Displaying outputs (M/O passed)

**Comment by ileppe** [comment]
@agahkarakuzu, I don't have the correct octave set-up yet (too old) but I will test everything soon and update here. In the meantime, a couple of things:
_General comment: the data .zip files all have a `__MACOSX/` folder, maybe we should make them on a Linux machine instead?_

- **charmed**
Batch example generation (M passed)
Batch example execution (Matlab fail: `fr` has to be in quotes `SimVaryPlot(SimResults,'fr','fr')`
Displaying outputs (M passed (after the SimVaryPlot is fixed))
- **noddi**
Batch example generation (M fail: the data is in a subdirectoy `noddi`, has to be in root `dti_data`)

**Comment by tanguyduval** [comment]
@agahkarakuzu i solved the issue of Octave 9c460dd6a2ad0e5eea81a3b175893407b8b554a7. please remove `if isoctave`

**Comment by agahkarakuzu** [comment]
@tanguyduval If we don't put more off by default, octave people won't be able to see the process. Because it waits till the end and displays everything at once. 

If you don't want this on the front page, maybe we can hide it somewhere in behind the scene.

**Comment by agahkarakuzu** [comment]
@ileppe  When I extract them with Matlab, _MACOSX file do not shot up, with Octave it does. Do you get this also with MATLAB?

**Comment by tanguyduval** [comment]
@agahkarakuzu these files are in the zip files. Let's put this issue to `low priority`. First thing is to get batch working :)

**Comment by ileppe** [comment]
pls add me to OSF as well, so I can help format the data, thx

**Comment by agahkarakuzu** [comment]
@tanguyduval I know, this MACOSX started popping up since I updated the OSF data (version 2).

**Comment by agahkarakuzu** [comment]
@ileppe Thank you for noticing that! :) I have only read+write permissions on OSF. I guess admin @tanguyduval can add you on the contributors list.

**Comment by agahkarakuzu** [comment]
@tanguyduval  I need to skip simulation parts on octave. Because qMRusage is not returning anything due to the our workaround on help documentation.

**Comment by agahkarakuzu** [comment]
I am still trying to understand what causes Octave to fail generating a complete batch example script. I guess there is something super fishy, it may take more than I expected. 

As a fallback procedure, I suggest uploading data folders along with batch examples that are generated in MATLAB. And inform Octave batch example test to use that script.

**Comment by agahkarakuzu** [comment]
Solved.

**Comment by agahkarakuzu** [comment]
@tanguyduval @mathieuboudreau @ileppe 

The most up-to-date batch example test results that I get by running BatchExample_test one by one for each model:

**PASSED (10):**

- charmed
- noddi
- b0_dem
- b1_dam
- mt_sat
- qmt_bssfp
- qmt_sirfse
- noise_level
- inversion_recovery
- mwf

**FAILED (3):**

- **dti**

`Error: EIG: matrix contains Inf or NaN values`
_Stairways to error:_
```
scd_model_dti:15 
fit:105 
FitData:102 

```
- **qmt_spgr**
Fitting voxels: Success
Computing missing Sf value… 
F.

`Error: failure: integrate_adaptive: Solving was not successful.  The iterative integration loop exited at time t = 0.000000 before the endpoint at tend = 0.010200 was reached.  This happened because the iterative integration loop did not find a valid solution at this time stamp.  Try to reduce the value of 'InitialStep' and/or 'MaxStep' with the command 'odeset'.`

_Stairways to error:_

```
integrate_adaptive:282 
  computeSf:10 
  GetSf:15 
  SPGR_Srp_fun:57 
  SPGR_SimCurve:64 
  plotModel:255 
  qMRshowOutput:30 
  qmt_spgr_batch:91 
  BatchExample_test>test_batch:27 
```

- **vfa_t1**

Missing data on OSF.

**Comment by mathieuboudreau** [comment]
Just did a quick pass on the spgr error; line 15 of GetSf should only get executed if the an value in the Sf table is "not a number". Yet the Sf table used should be the same as in for the protocol (ProtSfTable), which none of the values are nan's. So there might be two issues here: 1- why is the Sf table here not the same as the table from the Protocol, and (potentially) 2- why is there an error computing Sf values in Octave. 

I also came to another point of interest which is raised an alarm. @tanguyduval three months ago, you added a "varargin" argument to the CacheSf function:
https://github.com/neuropoly/qMRLab/blame/97af7cc3a9ca10d3ab342d061cc406974dc47ca4/Models_Functions/SPGRfun/functions/CacheSf.m#L1

However, you did not leave any comments indicating what these arguments can be, what purpose they use, how they need to be formatted, etc. Typically, varargins would be seperated at the very start of a function, but you pass it on to another function later on, which is very confusing for me: 

https://github.com/neuropoly/qMRLab/blame/97af7cc3a9ca10d3ab342d061cc406974dc47ca4/Models_Functions/SPGRfun/functions/CacheSf.m#L73
 
I only found out about this because CacheSf is called with  3 arguments instead of 1 in the Model: 

https://github.com/neuropoly/qMRLab/blob/97af7cc3a9ca10d3ab342d061cc406974dc47ca4/Models/Myelin_Imaging/qMT/SPGR.m#L323

Why are you passing an Sf table into CacheSf when the purpose of CacheSf should be to calculate Sf in the first place? Why is there a third argument that is of value 0? Could you clarify this? This is concerning to me, as you made the last two variables in CacheSf "varagin", which means they are optional. But within CacheSf, you pass them as the two  last arguments in BuildSfTable, which are not optional but required ( "oldSf" and "compute"). Which means that if someone calls CacheSf with only the required first parameter (protocolArg), the BuildSfTable call will crash, I think. Why were these two extra parameters needed to be added to CacheSf? Did they fix a bug, or were they for a feature?

**Comment by mathieuboudreau** [comment]
@tanguyduval looks like CacheSf does indeed work with one input; it passes my old CacheSf_Test here: https://github.com/neuropoly/qMRLab/blob/master/Test/Models_Functions/SPGRfun/functions/CacheSf_Test.m It was just confusing to me to pass one varargin from one function to another, I am more used to varargins being handled at the very start of a function.

Could you just clarify what the extra parameters are for, their purpose, and potential values so that they can be documented?

**Comment by tanguyduval** [comment]
@mathieuboudreau I added this varargin to test if we need to recompute SF table. I'll comment that tonight, but we could certainly improve this test (without changing cachesf). Before this test, there was no warning if the user forgot to update the SF table.  

Note that Cache SF is interpolating the protocol so I could not just compare the SF protocol and the current protocol.

**Comment by tanguyduval** [comment]
Another thing that I changed is to initialize SF as Nan's.. otherwise it was using 0 if user was canceling the SF computation.

Normally the default SF table was computed using the protocol of the example dataset. 

I see that the bug appears after the fitting of the dataset, in qMRshowOutput. Remember that the test skip the fitting after 2 voxels using ISTRAVIS environment variable, so all maps are 0. That might cause the bug.

**Comment by mathieuboudreau** [comment]
>Remember that the test skip the fitting after 2 voxels using ISTRAVIS environment variable, so all maps are 0. 

@tanguyduval I was not aware of this - thanks for noting this point! This may be the likely the culprit, because qMRshowOutput (where TRAVIS fails) uses the center voxel, which would not have been fitted in TRAVIS from the condition you mention above: https://github.com/neuropoly/qMRLab/blob/f0f15a6c68ea36866f885e806a956aaa154ca142/Common/qMRshowOutput.m#L19-L30

**Comment by tanguyduval** [comment]
@ileppe do you have a VFA_T1 dataset?? Missing data on OSF.

**Comment by ileppe** [comment]
@tanguyduval done!
but the batch fails, I think because the inputs are not in the right order:
`data = struct();
% B1map.nii.gz contains [128  128] data.
data.B1map=double(load_nii_data('/tmp/vfa_t1_demo/vfa_t1_data/B1map.nii.gz'));
% Mask.nii.gz contains [128  128] data.
data.Mask=double(load_nii_data('/tmp/vfa_t1_demo/vfa_t1_data/Mask.nii.gz'));
% VFAData.nii.gz contains [128  128    1    2] data.
data.VFAData=double(load_nii_data('/tmp/vfa_t1_demo/vfa_t1_data/VFAData.nii.gz'));`

**Comment by agahkarakuzu** [comment]
@ileppe vfa_t1 problem has been solved. Apparently, we've been lucky so far with the alphabetical order of input data.

FitData function takes the order of data struct fields into account to determine which data is the qData. I modified qMRgenpatch so that it arranges the order of data with reference to the MRIInputs. In this case, we should make sure that the first MRIinputs argument corresponds to the qData. 

More semantics. I guess documentation should inform users about this, or we should add something similar to that I've added on qMRgenBatch at the beginning of FitData. @tanguyduval Apparently I am not the one who comes up with the most concise solutions these days, any suggestions ? :) 

```
    MRIinputs = fieldnames(data);
    MRIinputs(structfun(@isempty,data))=[];
    MRIinputs(strcmp(MRIinputs,'hdr'))=[];
    qData = double(data.(MRIinputs{1}));
```

**Comment by agahkarakuzu** [comment]
VFA batch example crashes on ISTRAVIS 1. 

```
error: S(_,_,48,_): but S has size 128x128x1x2
error: called from
    extractvoxel at line 5 column 19
    qMRshowOutput at line 30 column 21
    vfa_t1_batch at line 72 column 1
stopped in /Users/Agah/Desktop/OctaveJN/qMRLab/Common/tools/extractvoxel.m at line 5
5:     S.(fields{ff}) = squeeze(S.(fields{ff})(Voxel(1),Voxel(2),Voxel(3),:));

```

**Comment by tanguyduval** [comment]
@agahkarakuzu for dti, it seems that the STD of input data is 0 in **one particular voxel**. Please restart the batch using in debug mode (run `dbstop if error` prior to the batch).

Yes, the first input needs to be the 4D data in FitData: the number of volumes is evaluated on MRIinputs{1}

VFA_t1 does not crash on my computer or on travis. Again run the batch in debug mode stp and contact me.

**Comment by tanguyduval** [comment]
All tests are now running on Matlab and Octave:
4e8c8e7e645835a7a8c116d45dadf0069c3c88b0
