### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#156]
Should have pop-up windows for the GUI when user does not input data properly:
 - [x] data not sampled the same way b548f9aa4de3de13b15baffc0539cf1b8db86b47
 - [x] missing input data or wrong format 72880602e82c2c5aae472d26f2a09262ec54066b
 - [x] protocol does not match data
 - [x] singleton dimensions #163

**Comment by mathieuboudreau** [comment]
[This default MATLAB function](https://www.mathworks.com/help/matlab/ref/errordlg.html) with a try-catch routine could work for this.

**Comment by ileppe** [comment]
Thanks! I guess it has to catch anytime a button that does a calculation is pressed: i.e.
- 'Fit Data'
- 'View Data Fit'

**Comment by mathieuboudreau** [comment]
I wonder if we could create a general function that does the error checking, and adapts automatically for each model?

**Comment by HarrisNami** [comment]
I am trying to do the B0 map, but it does not work. I can confirm that from master it works, but when I switch branches to the error-catch branch it doesn't work. I also tried B1 and I get the same error as shown in the attached image.  

/Users/hanam/Desktop/Error-catch B0 error.png

**Comment by HarrisNami** [comment]
I cannot run the B0 map through the error-catch branch. I tried it in master and it works, but once I switch I get the error shown in the image. I tried with B1 as well and get the same error. 

![error-catch b0 error](https://user-images.githubusercontent.com/29234406/36691446-4a81e208-1b03-11e8-8e8e-68e81c6714d4.png)

**Comment by ileppe** [comment]
@HarrisNami You guys and your old matlab versions! :p  this was included in Matlab R2016b. For now, please replace `newline` with `sprintf('\n')`. I will fix this is my next commit. Thanks for pointing that out.

**Comment by HarrisNami** [comment]
Ok so I did a git pull for the latest updates, but I am still getting errors. The first one is for the B0, it says my data does not match, which is weird because when I do it on the master it works (which is what the background image you see is), but on error-catch it does not work. The second image is the error I get when I try and run the B1. 

![screen shot 2018-02-27 at 4 06 17 pm](https://user-images.githubusercontent.com/29234406/36755015-d0641852-1bd8-11e8-9aa6-61b5df682b93.png)

![screen shot 2018-02-27 at 4 08 52 pm](https://user-images.githubusercontent.com/29234406/36755021-d4bb42b8-1bd8-11e8-9b4d-cfc1911390fc.png)

**Comment by ileppe** [comment]
@HarrisNami this ties back to this issue #163 with singleton dimensions. I have to incorporate a way to handle it properly, I'll work on it!
