### ISSUE TITLE
Error when loading the results from a file.

### ISSUE THREAD

**Issue by TommyBoshkovski** [neuropoly/qMRLab#160]
An error is thrown when trying to load results from a file.

Undefined function or variable 'S'.

Error in qMRloadObj (line 5)
Model = str2func(S.ModelName); Model = Model();

**Comment by mathieuboudreau** [comment]
Two things:

* @TommyBoshkovski  The bug appears to be due to a miss "else" condition for when the argument of that function is already a struct - S should be set to the argument ("filename").

* @tanguyduval [checkanteriorver.m](https://github.com/neuropoly/qMRLab/blob/f12bf346a199e5217ca1d4d4af947d6fbe2fa27f/Test/Common/checkanteriorver.m) and [qMRloadObj.m](https://github.com/neuropoly/qMRLab/blob/f12bf346a199e5217ca1d4d4af947d6fbe2fa27f/Test/Common/qMRloadObj.m) were created in qMRLab/Test/Common/ – can you confirm that they were actually intended to be placed in qMRLab/Common/ ?

I handled both these things in branch [loadbug](https://github.com/neuropoly/qMRLab/tree/loadbug). I'll create a pull request and make you as the reviewer Tommy; please pull the branch and verify that it is now working correctly for you.
