### ISSUE TITLE
MTsat method requires B1 file

### ISSUE THREAD

**Issue by hagiwara-akifumi** [neuropoly/qMRLab#168]
it would be convenient to have this input optional.

**Comment by agahkarakuzu** [comment]
@hagiwara-akifumi Thank you for the input, we will consider this in our next meeting.

**Comment by tanguyduval** [comment]
@hagiwara-akifumi Thank you for the feedback.
B1 is optional, just leave empty.
We need to:
- add B1 map to MTSAT documentation
- Add colorcoding for optional intputs #83

**Comment by tanguyduval** [comment]
Optional inputs are now in light gray, 
![image](https://user-images.githubusercontent.com/7785316/36485996-bdc09a6e-171d-11e8-8c95-03cf507c127f.png)

To do this, I added a function in AbstractModel called `get_MRIinputs_optional` that searches in the header if MRIInputs are between brackets somewhere:
````
        function optionalInputs = get_MRIinputs_optional(obj)
            % Optional input? Search in help
            optionalInputs = false(1,length(obj.MRIinputs));
            hlptxt = help(obj.ModelName);
            for ii = 1:length(obj.MRIinputs)
                if ~isempty(strfind(hlptxt,['(' obj.MRIinputs{ii} ')']))
                    optionalInputs(ii)=true;
                end
            end
        end
````
commit 4debca2dcb9a47c521fdca7b6e8732c165894798

**Comment by ileppe** [comment]
@tanguyduval I had also made a change in the 'error-catch' branch to address this issue. In my implementation, I added a 'reqInputs' property to the model. Do you think the headers are going to be sufficiently trust-worthy?

**Comment by mathieuboudreau** [comment]
We should discuss sometime soon how to clearly distinguish inputs that are optional, and input that are optional but recommended. We might need to integrate some "learn more" buttons (maybe a question mark?) next to the optional inputs (or all), to give brief descriptions of them as well as important considerations. The real issue will be how to implement something like this without cluttering the GUI, since it is very tight already.

**Comment by tanguyduval** [comment]
@ileppe sorry about that. I used the header because it prevents a duplication of the information (between the header and the code). Also, it prevents from adding a new property. Feel free to use your solution, or to improve mine (e.g. by using Gab header parser).

@mathieuboudreau I think we can add these considerations in the header of the model. 
- Currently, optional arguments are defined using brackets. We can introduce double brackets, for instance, to distinguish between recommended or totally optional.
- We can detail the important consideration in the same header
- If we use Gab parser, a question mark can be added in the file browser panel that will display these recommendations.

Best

**Comment by tanguyduval** [comment]
![image](https://user-images.githubusercontent.com/7785316/38028989-e2bd82e0-3294-11e8-9dcf-4ed352099162.png)

Play with double parenthesis for optional arguments such as Mask
