### ISSUE TITLE
Random things that could/should be fixed in documentation

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#175]
-1 [x ] by default `qMRshowOutput` in the batch shows the fit in the center of the middle slice, but this often ends up being in the central sulcus where fits might look very weird e.g.
![screen shot 2018-03-01 at 15 57 22](https://user-images.githubusercontent.com/28764708/36869297-54b27c84-1d69-11e8-9fef-333cf1485e48.png)
-2. [x] `GenerateDocumentation` should create a `Data` folder if it does not exist
-3. [x] matlab2014b does not support downloading from OSF @agahkarakuzu I think you are working on this, I am just putting a tick box ;)
-4. [ x] the range of the figures if often odd, not showing proper contrast e.g. B0map would be more informative if shown from -50,50
![screen shot 2018-03-01 at 16 29 41](https://user-images.githubusercontent.com/28764708/36870677-ddd03156-1d6d-11e8-9b2f-569fb78ee6fb.png)

**Comment by tanguyduval** [comment]
@ileppe concerning DTI:
1- "fit takes forever". This is not because we are doing non-linear fitting (even with 10 volumes fitting will be slow). This is a general issue and implementing in c++ would not help much... we need to linearize just as AMICO. However, the problem with the simple linear solution is that it is biased by the Rician Noise. Someone should work on this issue. A temporary solution would be to propose to skip the non-linear fitting lines:
https://github.com/neuropoly/qMRLab/blob/f12bf346a199e5217ca1d4d4af947d6fbe2fa27f/Models/Diffusion/dti.m#L110-L126

2. `FA, MD, residue` are products of the fitting variables. `xnames` include only the unknown variables that need to be fitted. 
But you are right, DTI should have more fitting variables: 6 variables instead of 3 (3 orthogonal vectors of diffusion)

**Comment by ileppe** [comment]
@tanguyduval thank you for the clarifications!
1. What do you think about doing the linear fitting by default, and allow the user to select the non-linear option to avoid the bias? I feel the average user will be confused by this and how long the fitting is taking. It would be great to include this information in the header, do you have a reference?
2. Ok, as a general rule, should we say `xnames` includes all outputs in `FitResults`, even if they can be inferred from other outputs?

**Comment by tanguyduval** [comment]
@ileppe 
1. I agree because DTI are usually acquired at relatively low b-value, high SNR. But we should create an issue to linearize Models, taking into account noise correction.
2. We cannot do that, because xnames are used in the GUI to define ub, lb. If two interlinked variables exist, there will be some conflicts...

**Comment by ileppe** [comment]
@tanguyduval 
1. Ok, let's talk more offline about this
2. I see. So I will just make sure that the 1st field of `FitResults` is `FA`.

**Comment by agahkarakuzu** [comment]
@ileppe if there is not any difference between the @HarrisNami 's R2014b and others then yes :)
ver>R2014b must be satisfied. 

`GenerateDocumentation` will be freed from Data folder . We will work on this with @gab-berest on Monday. 

Your xnames suggestion is now under [wiki page](https://github.com/neuropoly/qMRLab/wiki/Guideline:-Adding-a-new-Model#-property-2-xnames). Although it is specific to dti model, gives clue about the issue.

**Comment by spinicist** [comment]
Re: non-linear versus linear in DTI, the FSL's `dtifit` provides a weighted least-squares option `--wls` which is supposed to account for the Rician noise with little speed penalty. However, I've never actually managed to track down the exact weighting used or which reference it is from.

**Comment by ileppe** [comment]
@agah Re: please remove `Note: xnames should include all the outputs i.e. FA, MD,residue etc. (example from dti).` We actually cannot do that (see Tanguy's comment), we just have make sure the primary output is in the 1st field of `FitResults`. e.g. in the case of `dti` the 1st assignment to `FitResults` is `FA`. I did this in 3f1dcc9

**Comment by agahkarakuzu** [comment]
@ileppe I see, removing right away.

**Comment by ileppe** [comment]
thanks @spinicist. In the FSL archives I see they refer to this for the `--wls` option: http://onlinelibrary.wiley.com/wol1/doi/10.1002/hbm.20076/full, I would have to delve deeper though. So please correct me if I'm wrong, we would like to support the following options:
- linear least-squares (LS) -- > suitable for low bval
- weighted LS (as in FSL) --> suitable for high bval
- weighted Non-LS (which is what is implemented now?) -->potentially even better for very high bval?

**Comment by tanguyduval** [comment]
Thank you Tobias, the weighted average is also a nice option I agree.

@ileppe , this is correct. I would detail as follow:
Weighted-Average + linear fit:
Pros:
- Does not require exact SNR measure
- No assumption on noise characteristic (e.g. Rician or Non-central Chi)
Cons:
- Only an approximation (not a perfect solution), which is problematic if the entire dataset is low SNR (e.g. high b-value diffusion dataset).

Non-linear fitting (objective function = rician likelihood)
Pros:
- perfect solution
Cons:
- Assumes noise characteristic (e.g. Rician) 
- Need to compute SNR
- Slow

Rician bias correction + linear fit:
Pros:
- Close to the perfect solution (We correct rician bias assuming: noisy signal = expected signal)
Cons:
- Need to compute SNR
- Assumes noise characteristic (e.g. Rician) 

We can usually assume that noise is Rician because most people use "adaptive combine"
SNR can be computed easily using ~5 repetitions of the same measure.

NOTE 1: THIS DISCUSSION IS VALID FOR ALL VOXELWISE MODELS (although high SNR datasets do not suffer much from rician bias)
NOTE 2: THE NOISE IMPACT ON THE FITTED METRICS CAN BE ASSESSED USING SENSITIVITY ANALYSIS.

**Comment by ileppe** [comment]
@tanguyduval thanks for the in-depth discussion! I'm moving it to a separate issue #176

**Comment by ileppe** [comment]
In order to resolve issues 1 and 4 above (related to how `showOuput.m`) I have to update the `FitResults.mat`on OSF (since this is what is being loaded and displayed for the documentation). @agahkarakuzu do you have a script to do this automatically or did you manually create the .zip files?
