### ISSUE TITLE
Output of B0 unwrapped phase

### ISSUE THREAD

**Issue by HarrisNami** [neuropoly/qMRLab#199]
Would like to have the B0 unwrapped phase as an output after running the analysis. This would help in the investigation of any potential issues we see with the B0 field.

Thanks!

**Comment by mathieuboudreau** [comment]
Great suggestion @HarrisNami !

@agahkarakuzu since we're currently using the phase unwrapping functions for B0 field mapping, but also will be using it in the near future for QSM, do you think we should maybe make it its own model? Or possibly, make it it's own abstract model that things models like QSM and field mapping could inherit the methods from?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau totally agree, having more core functions would give us better modularity and consistency. We can also prepare an UML diagram before class relationships become more complicated.
