### ISSUE TITLE
installation: integrate MoxUnit as subtree instead of submodule

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#69]
~~~
git submodule update --init --recursive
~~~

**Comment by tanguyduval** [comment]
submodule is not well managed by github yet (download zip --> no submodule!). I added MoxUnit directly as a folder in External

**Comment by spinicist** [comment]
If you want the modules to appear for the user immediately on download/clone, isn't a git subtree what you want instead of a submodule?

I use submodules in my C++ quantitative stuff (github.com/spinicist/QUIT), but that's because people may have them on their system already and prefer to link against them.

For a Matlab project, I guess you always want the files present so a subtree is more appropriate?

**Comment by jcohenadad** [comment]
thank you @spinicist 
i guess we can reopen this issue and change the title for suggesting the possibility to link this external repo as a subtree

**Comment by tanguyduval** [comment]
done in ada500a950cb8689a9c0a5300de2074ecbf18f95
