### ISSUE TITLE
qMT-bSSFP fit fails

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#77]
The bSSFP simulation fails:
````
Testing bSSFP simulation option:
  scalar structure containing the fields:
    SNR =  1000
    Method = Block equation
    ResetMz = 0

failure: FitResults =
  scalar structure containing the fields:
    F =  0.30000
    kr =  16.260
    T2f =  0.025757
GroundTruth =
  scalar structure containing the fields:
    F =  0.10000
    kr =  30
    T2f =  0.040000
````

Analytical equation doesn't fit correctly the block equation.
Possible reasons:
- protocol is not optimal 
- two many parameters to fit 
- analytical equation is wrong

**Comment by tanguyduval** [comment]
https://travis-ci.org/neuropoly/qMRLab/builds/284259679?utm_source=email&utm_medium=notification

**Comment by tanguyduval** [comment]
The error in the simulation of block equations is due to the fact that various Trf in the default protocol is not well managed.
Is it normal to have various Trf in the protocol? @jfcabana @mathieuboudreau 
![image](https://user-images.githubusercontent.com/7785316/31301759-60143d9a-aaca-11e7-994a-56060cb0f875.png)

**Comment by jfcabana** [comment]
Yes, alpha and Trf are free parameters. The method uses a combination of fixed Trf / variable alpha and fixed alpha / variable Trf. Simulation and fitting of bSSFP protocol used to work fine. If this is the same demo protocol than what was built in qMTLab, I know for sure it was working well.

**Comment by mathieuboudreau** [comment]
@tanguyduval @jfcabana I don't have experience using the bSSFP portion of qMTLab unfortunately. The best I can thing of is to generate signals/fits at previous commits until you find where it differs from your current results (likely before June 2017). 

Having seen recently that the SPGR models had some missing features when it was converted to a model, and being confident that @jfcabana had it working when it was published (*and that bSSFP was barely touched since), my guess is that a similar issue in converting the old bSSFP code to the model template might have not been done correctly, or has some code/features missing.

**Comment by spinicist** [comment]
`git bisect` is your friend in these situations!

**Comment by tanguyduval** [comment]
Thank you, everyone, for these clarifications. 
I found these issues that caused the problem :
- small error in default bSSFP protocol 4012650c78aa92a1eecc213d11346f7626291c6a
- Fitting tolerance was too high ca45200d97dc405ded42abb303a940d4dd8594bf
- SPGR fitting boundary: 1ed613c5263e9dadea9d9a0fc0d30751c7581959

I guess Ian didn't put R1f*T2f because he saw no effect on SledPike... that's a conclusion some people might guess... I create a new issue to hide the option `Fix R1f*T2f`

**Comment by mathieuboudreau** [comment]
Great finds Tanguy. I had encountered the SPGR fitting boundary (too low for kf) previously; I thought I had fixed in in Master. The fix might have gotten lost during the transition to the model, thanks for fixing it again!

**Comment by mathieuboudreau** [comment]
[removed my last comment]

@tanguyduval , leaving the upper bound for kr at a high values (at least 100) in your SPGR fix (which you reverted) is required, I'm the one who set the up to 500 this summer. This is because the normal values of kr in vivo are actually around 30, and making the upper bound the average value will bias all the other parameters when trying to fit non-demo data.

Did the unit test give you an error with the high ub value? Or did you simply see the old values and chose to revert them?

**Comment by tanguyduval** [comment]
I changed F and kr to match qMTLab. Now corrected in commit 6cfe5088471e505f7084d51226aa637f226997c2

I reduce the number of MT pulse for faster Block equation simulation. Travis was crashing because it takes more than 10min.. I put back default number to 600 and updated travis config to allow 30min of simulations instead df4dbd574ba34368bfc55ec5631076a7fb689740

**Comment by mathieuboudreau** [comment]
Thanks for the fix! Yeah it's a pickle for the default number of preparation pulses, should we keep a good default value so that the user isn't mislead into using too small of a number when designing their experiment at the expense of an extremely long test, or vice versa? 

Is there possibly a way to force a smaller number of that parameter in the travis test, but leave the default at a good value? I know for the unit tests like I write them I'd be able to do that to shorten the test time, but am unsure if it would be possible with your automated unit tests.

**Comment by tanguyduval** [comment]
bSSFP fit is unstable. Octave finds a global minimum (I checked) that is far from the groundtruth (input of the Sim_Single_Voxel).
Error of Travis:
````
FitResults =
  scalar structure containing the fields:
    F =  0.23566
    kr =  22.856
    R1f =  1.8342
    R1r =  1.8342
    T2f =  0.020005
GroundTruth =
  scalar structure containing the fields:
    F =  0.10000
    kr =  30
    R1f =  1
    R1r =  1
    T2f =  0.040000
````
 

R1f seems to compensate kr and F... For a quick fix I fixed R1f to 1.
I can do that for the simulation part only (currently I set that for the default bSSFP fit in d020cdbecf5878aedfef388b0308d2944149e924).

Thanks for the feedback @mathieuboudreau 
I can set a lower number of pulses for the simulation. But allowing more time for Travis solved the problem. I'll do that if needed.

**Comment by tanguyduval** [comment]
Note that I fix R1f to 1 because normally we need a R1map to fix R1f. We could make the R1map mandatory if the fit is unstable without this map.

**Comment by mathieuboudreau** [comment]
@tanguyduval I'm not sure for bSSFP, but it's generally agreed that for SPGR qMT, a T1meas is required to properly fit the qMT parameters, as MT-weighted measurements alone don't constrain all the parameters. [Sled's 2001 paper](http://onlinelibrary.wiley.com/doi/10.1002/mrm.1278/abstract) talks about it before Eq. 7, and he cites [Henkelmans 1993](http://onlinelibrary.wiley.com/doi/10.1002/mrm.1910290607/abstract) paper (who in turn cites [Caine 1991](http://www.sciencedirect.com/science/article/pii/002223649190169T) as noted this first). 

All this to say that I think it would be a very fair assumption to require the R1 map for the bSSFP (and other qMT) methods.

@jfcabana do you know if bSSFP recommended to leave R1f as a free parameter, or did you just give this option (to fit for it) in case the user didn't have an R1map? If it's the latter, then I would opt for removing that option, as the fit may not be reliable, as @tanguyduval rediscovered.

**Comment by tanguyduval** [comment]
I set `use R1map` to true by default
2fa07db51e86b4a3a605ccfa4e71f51564ec4cb7

**Comment by spinicist** [comment]
Yes, Gloor's original SSFP qMT [paper](http://doi.wiley.com/10.1002/mrm.21705) uses a separate R1/T1 map (acquired with DESPOT1/VFA).

**Comment by jfcabana** [comment]
Yes, the paper does mention that you need it:

"From the overall similarity of Equations [10] and [1], it is seen that the main two-pool bSSFP signal characteristics rely on the combination T2/T1 (7). As a result, reliable T1 or T2 parameter estimation from Equation [10] thus requires an independent determination of either T1 or T2..."

I probably let the option to be able to fit without it in case you don't have it, but I agree it might not be a good idea to allow for that if the results are totally unreliable.
